lib/shorty_web/router.ex
defmodule ShortyWeb.Router do
  use ShortyWeb, :router

  pipeline :browser do
    plug RemoteIp
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ShortyWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ShortyWeb do
    pipe_through :browser

    live "/", PageLive, :index
    live "/shortened_links", ShortenedLinkLive.Index, :index
    live "/shortened_links/new", ShortenedLinkLive.Index, :new
    live "/shortened_links/:id/edit", ShortenedLinkLive.Index, :edit

    live "/shortened_links/:id", ShortenedLinkLive.Show, :show
    live "/shortened_links/:id/show/edit", ShortenedLinkLive.Show, :edit

    live "/views", ViewsLive.Index, :index

    get "/:path", RedirectionController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", ShortyWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ShortyWeb.Telemetry
    end
  end
end

lib/shorty_web/live/live_helpers.ex
defmodule ShortyWeb.LiveHelpers do
  import Phoenix.LiveView.Helpers

  @doc """
  Renders a component inside the `ShortyWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal @socket, ShortyWeb.ShortenedLinkLive.FormComponent,
        id: @shortened_link.id || :new,
        action: @live_action,
        shortened_link: @shortened_link,
        return_to: Routes.shortened_link_index_path(@socket, :index) %>
  """
  def live_modal(socket, component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(socket, ShortyWeb.ModalComponent, modal_opts)
  end
end

lib/shorty_web/live/modal_component.ex
defmodule ShortyWeb.ModalComponent do
  use ShortyWeb, :live_component

  @impl true
  def render(assigns) do
    ~L"""
    <div id="<%= @id %>" class="phx-modal"
      phx-capture-click="close"
      phx-window-keydown="close"
      phx-key="escape"
      phx-target="#<%= @id %>"
      phx-page-loading>

      <div class="phx-modal-content">
        <%= live_patch raw("&times;"), to: @return_to, class: "phx-modal-close" %>
        <%= live_component @socket, @component, @opts %>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
end

lib/shorty_web/live/page_live.ex
defmodule ShortyWeb.PageLive do
  use ShortyWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, query: "", results: %{})}
  end

  @impl true
  def handle_event("suggest", %{"q" => query}, socket) do
    {:noreply, assign(socket, results: search(query), query: query)}
  end

  @impl true
  def handle_event("search", %{"q" => query}, socket) do
    case search(query) do
      %{^query => vsn} ->
        {:noreply, redirect(socket, external: "https://hexdocs.pm/#{query}/#{vsn}")}

      _ ->
        {:noreply,
         socket
         |> put_flash(:error, "No dependencies found matching \"#{query}\"")
         |> assign(results: %{}, query: query)}
    end
  end

  defp search(query) do
    if not ShortyWeb.Endpoint.config(:code_reloader) do
      raise "action disabled when not in development"
    end

    for {app, desc, vsn} <- Application.started_applications(),
        app = to_string(app),
        String.starts_with?(app, query) and not List.starts_with?(desc, ~c"ERTS"),
        into: %{},
        do: {app, vsn}
  end
end

lib/shorty_web/live/shortened_link_live/form_component.ex
defmodule ShortyWeb.ShortenedLinkLive.FormComponent do
  use ShortyWeb, :live_component

  alias Shorty.Links

  @impl true
  def update(%{shortened_link: shortened_link} = assigns, socket) do
    changeset = Links.change_shortened_link(shortened_link)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"shortened_link" => shortened_link_params}, socket) do
    changeset =
      socket.assigns.shortened_link
      |> Links.change_shortened_link(shortened_link_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"shortened_link" => shortened_link_params}, socket) do
    save_shortened_link(socket, socket.assigns.action, shortened_link_params)
  end

  defp save_shortened_link(socket, :edit, shortened_link_params) do
    case Links.update_shortened_link(socket.assigns.shortened_link, shortened_link_params) do
      {:ok, _shortened_link} ->
        {:noreply,
         socket
         |> put_flash(:info, "Shoretened link updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_shortened_link(socket, :new, shortened_link_params) do
    case Links.create_shortened_link(shortened_link_params) do
      {:ok, _shortened_link} ->
        {:noreply,
         socket
         |> put_flash(:info, "Shoretened link created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/shorty_web/live/shortened_link_live/index.ex
defmodule ShortyWeb.ShortenedLinkLive.Index do
  use ShortyWeb, :live_view

  alias Shorty.Links
  alias Shorty.Links.ShortenedLink

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :shortened_links, list_shortened_links())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Shoretened link")
    |> assign(:shortened_link, Links.get_shortened_link!(id))
  end

  defp apply_action(socket, :new, _params) do
    random_string = :crypto.strong_rand_bytes(16) |> Base.encode64() |> binary_part(0, 16)

    socket
    |> assign(:page_title, "New Shoretened link")
    |> assign(:shortened_link, %ShortenedLink{shortened_path: random_string})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Shortened links")
    |> assign(:shortened_link, nil)
  end

  @impl true
  @spec handle_event(<<_::48>>, map, Phoenix.LiveView.Socket.t()) ::
          {:noreply, Phoenix.LiveView.Socket.t()}
  def handle_event("delete", %{"id" => id}, socket) do
    shortened_link = Links.get_shortened_link!(id)
    {:ok, _} = Links.delete_shortened_link(shortened_link)

    {:noreply, assign(socket, :shortened_links, list_shortened_links())}
  end

  defp list_shortened_links do
    Links.list_shortened_links()
  end
end

lib/shorty_web/live/shortened_link_live/show.ex
defmodule ShortyWeb.ShortenedLinkLive.Show do
  use ShortyWeb, :live_view

  alias Shorty.Links

  @link_views_topic "link_views"

  @impl true
  def mount(_params, _session, socket) do
    ShortyWeb.Endpoint.subscribe(@link_views_topic)

    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:shortened_link, Links.get_shortened_link!(id))}
  end

  @impl true
  def handle_info(%{topic: @link_views_topic, payload: %{link_id: link_id}}, socket) do
    if link_id == socket.assigns.shortened_link.id do
      {:noreply, assign(socket, :shortened_link, Links.get_shortened_link!(link_id))}
    else
      {:noreply, socket}
    end
  end

  defp page_title(:show), do: "Show Shoretened link"
  defp page_title(:edit), do: "Edit Shoretened link"
end

lib/shorty_web/live/views_live/index.ex
defmodule ShortyWeb.ViewsLive.Index do
  use ShortyWeb, :live_view

  alias Shorty.Links

  @link_views_topic "link_views"

  @impl true
  def mount(_params, _session, socket) do
    ShortyWeb.Endpoint.subscribe(@link_views_topic)

    {:ok, assign(socket, :views, Links.list_views())}
  end

  @impl true
  def handle_info(%{topic: @link_views_topic, payload: _payload}, socket) do
    {:noreply, assign(socket, :views, Links.list_views())}
  end
end

lib/shorty_web/live/views_live/view_metrics_component.ex
defmodule ShortyWeb.ShortenedLinkLive.ViewMetricsComponent do
  use ShortyWeb, :live_component

  def view_browser(view) do
    Browser.name(view.user_agent)
  end

  def unique_views(views) do
    views
    |> Enum.map(& &1.ip)
    |> Enum.uniq()
    |> Enum.count()
  end

  def views_by_place(views) do
    views
    |> Enum.map(&{&1.country, &1.city})
    |> Enum.frequencies()
    |> sort_by_counts()
    |> format()
  end

  def views_by_link(views) do
    views
    |> Enum.map(& &1.link.name)
    |> Enum.frequencies()
    |> sort_by_counts()
    |> format()
  end

  def sort_by_counts(enum_with_count) do
    enum_with_count
    |> Enum.sort_by(fn {_, count} -> count end, :desc)
  end

  defp format(data) do
    Enum.map(data, fn
      {{country, city}, views} -> [country, city, views]
      {label, views} -> [label, views]
    end)
  end
end

lib/shorty_web/live/shortened_link_live/form_component.html.leex
<div class="shortened_link-form_component">
  <%= live_patch raw("&times;"), to: @return_to, class: "phx-modal-close" %>
  <h2><%= @title %></h2>

  <%= f = form_for @changeset, "#",
    id: "shortened_link-form",
    phx_target: @myself,
    phx_change: "validate",
    phx_submit: "save" %>

    <%= label f, :name %>
    <%= text_input f, :name %>
    <%= error_tag f, :name %>

    <%= label f, :shortened_path %>
    <%= text_input f, :shortened_path %>
    <%= error_tag f, :shortened_path %>

    <%= label f, :original_url %>
    <%= text_input f, :original_url %>
    <%= error_tag f, :original_url %>

    <%= submit "Save", phx_disable_with: "Saving..." %>
    <%= live_patch "Cancel", to: @return_to, class: "button button-outline" %>
  </form>
</div>

lib/shorty_web/live/shortened_link_live/index.html.leex
<%= if @live_action in [:new, :edit] do %>
  <%= live_component @socket, ShortyWeb.ShortenedLinkLive.FormComponent,
    id: @shortened_link.id || :new,
    title: @page_title,
    action: @live_action,
    shortened_link: @shortened_link,
    return_to: Routes.shortened_link_index_path(@socket, :index) %>
<% else %>
  <h1>Listing Shortened links</h1>

  <span><%= live_patch "New Shoretened link", to: Routes.shortened_link_index_path(@socket, :new), class: "button" %></span>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Shortened link</th>
      <th>Original url</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="shortened_links">
    <%= for shortened_link <- @shortened_links do %>
      <tr id="shortened_link-<%= shortened_link.id %>">
        <td><%= shortened_link.name %></td>
        <td><%= link Routes.redirection_url(@socket, :show, shortened_link.shortened_path),
                     to: Routes.redirection_url(@socket, :show, shortened_link.shortened_path) %></td>
        <td><%= link shortened_link.original_url, to: shortened_link.original_url %></td>

        <td>
          <span><%= live_redirect "Show", to: Routes.shortened_link_show_path(@socket, :show, shortened_link) %></span>
          <span><%= live_patch "Edit", to: Routes.shortened_link_index_path(@socket, :edit, shortened_link) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: shortened_link.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

lib/shorty_web/live/shortened_link_live/show.html.leex
<%= if @live_action in [:edit] do %>
  <%= live_component @socket, ShortyWeb.ShortenedLinkLive.FormComponent,
    id: @shortened_link.id,
    title: @page_title,
    action: @live_action,
    shortened_link: @shortened_link,
    return_to: Routes.shortened_link_show_path(@socket, :show, @shortened_link) %>
<% else %>
  <h1>Show Shoretened link</h1>

  <ul>

    <li>
      <strong>Name:</strong>
      <%= @shortened_link.name %>
    </li>

    <li>
      <strong>Shortened path:</strong>
      <%= @shortened_link.shortened_path %>
    </li>

    <li>
      <strong>Original url:</strong>
      <%= @shortened_link.original_url %>
    </li>

  </ul>

  <span><%= live_patch "Edit", to: Routes.shortened_link_show_path(@socket, :edit, @shortened_link), class: "button" %></span>
  <span><%= live_redirect "Back", to: Routes.shortened_link_index_path(@socket, :index) %></span>
<% end %>

<%= live_component @socket, ShortyWeb.ShortenedLinkLive.ViewMetricsComponent, id: :view_metrics, views: @shortened_link.views, views_by_link: false %>